### ISSUE TITLE
TODO List: Parallel Port Lab

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/CO326-2022#1]
- [ ] Check the Remote Login 
- [ ] Purchase Web Camera 
- [ ] Network in the lab
- [ ] 4 x Machines with Parallel port
- [ ] Solder 3 units + 1 unit with IC setup
